### ISSUE TITLE
Outline Object not expandabkle?

### ISSUE THREAD

**Issue by lublak** [Descolada/Acc-v2#2]
Hi i found you Acc and UIA scripts :) they are awesome!
Now i have an OutlineObject (in UAI its called Type:"TreeItem")
But if i try to call Expand or get the Expand sate it alweys says that there is not method for this object. But for me its importend to expand them (i can call just DoDefaultAction but here its impossible to check the current state, and it would be and issue if the item gets collapsed not expanded)

**Comment by Descolada** [comment]
Hello! 
Are you using Acc or UIA? They are very different:
1) In Acc there is no Expand() method. Instead only DoDefaultAction(), and sometimes you can get the expand/collapse state with `Element.State`
2) In UIA the ExpandCollapsePattern has the Expand() and Collapse() methods, which you should be able to call with `Element.Expand()` (make sure you have an uptodate UIA.ahk, I've updated it a LOT recently). It also has the ExpandCollapseState to get the current state.

**Comment by lublak** [comment]
@Descolada 
I used mostly UIA. I switched to aac because i have no idea what im doing. 
I found this example and tried it:https://github.com/Descolada/UIA-v2/blob/main/Examples/Example10_ExpandCollapsePattern.ahk
![grafik](https://user-images.githubusercontent.com/44057030/218263694-36239cb9-887d-4551-b59c-269942e17321.png)

Now i try to switch to aac and hope it works here? Because its older and more supported by microsoft for old guis?

And okay to UIA its easier for me to use i think? Currenlty for me its not importend. AAC or UIA both is fine.

And im up to date. I downloaded it just now!

**Comment by lublak** [comment]
Ah! Okay now i get it :3 acc works fine. UAI is not working because method ExpandCollapseState is not found.

acc:
```ahk
ep := bdeadminEl.FindElement({Name: "Konfiguration", Role: 36}).State

MsgBox(ep & Acc.State.Expanded == Acc.State.Expanded) // returns 1! nice!
MsgBox(ep & Acc.State.Collapsed == Acc.State.Collapsed)
```

so i change my code from uai to acc

**Comment by lublak** [comment]
@Descolada i think we can move this issue to UIA than :)

**Comment by Descolada** [comment]
I would actually recommend sticking to UIA, you will have better performance and reliability with that.
I noticed that you Acc code differs from UIA code - in one you are checking the state for "Konfiguration" element, but in UIA "Treiber" element instead. Are you sure you got the correct element in UIA?
1) Update UIA.ahk if you haven't already
2) Inspect the element with UIAViewer (run UIA.ahk alone), see if it has the ExpandCollapsePattern, and try double-clicking Expand() or Collapse() to check whether it's working
3) After using FindElement, make sure you found the correct one, using Highlight() or Dump() or DumpAll(). 
4) Check whether the found element has IsExpandCollapsePatternAvailable property as 1 (true). 
5) If IsExpandCollapsePatternAvailable is 1 but you still get the error, try `element.ExpandCollapsePattern.ExpandCollapseState` instead (although it shouldn't make a difference, perhaps you've discovered an unknown bug?)

If Acc was able to get the expand-collapse state, then UIA should be able to as well...
