### ISSUE TITLE
Viewer Copy Function

### ISSUE THREAD

**Issue by crmarksiv** [Descolada/Acc-v2#5]
I would like to suggest a change in the Acc viewer copy function to output the copied information into a format compatible with the Condition format. Example: instead of  Name: Overwrite   output  { Name:'Overwrite'}

**Comment by Descolada** [comment]
Implemented by commit [4b67612](https://github.com/Descolada/Acc-v2/commit/4b6761201be6236f8be25eef500ec804987b51f2). It doesn't include the brackets, because typing those manually is trivial (at least in VSCode), and is more in line with UIAViewer as well.
